### PR TITLE
Change the school eligibility checkers to allow special schools with unspecified phases

### PR DESCRIPTION
**Pull request by erbridge**
Most special schools have a "Not Applicable" education phase, so this adds support for those schools.

We use the school type, rather than the school type group for determining if a school is a special school because e.g. free special schools are grouped under free schools, and so would be left out. There maye be other examples.

### CODE REVIEW

**Comment by erbridge** [comment]
[Change the school eligibility checkers to allow SEN schools with any phase](https://trello.com/c/gbUiELuD/446-change-the-school-eligibility-checkers-to-allow-sen-schools-with-any-phase)

**Comment by erbridge** [comment]
We have not. How do I get the dump of eligible schools and who do I send it to? Perhaps someone could help me do that?

**Comment by tekin** [comment]
I'd use a crude script in the Rails console. Something like:

```ruby

**Comment by tekin** [comment]
I'd use a crude script in the Rails console. Something like:

```ruby
Rails.logger.level = Logger::WARN
School.all.each do |school|
  puts [school.urn, school.name].join(" - ") if Tslr::SchoolEligibility.new(school).check
end;nil
```

As to the person, probably start with Chris Cuff or George Poulton.

**Comment by robbiepaul** [comment]
This is what I used previously when exporting eligible schools:
```
require "csv"
CSV.open("tmp/schools.csv", "wb") do |csv|
  csv << School.attribute_names
  School.includes(:local_authority).select(&:eligible_for_tslr?).each do |school|
    csv << school.attributes.values
  end
end
```

**Pull request merged**
