### PR TITLE
Upcase existing National Insurance numbers

### PR DESCRIPTION
**Pull request by lawrence-dxw**
This is the data migration mentioned in 7e50b1e.

### CODE REVIEW

**Comment by lawrence-dxw** [comment]
I wanted to run a single SQL query which updates all the records, so I just used raw SQL, and I `ActiveRecord::Base.connection.execute` is the only way that I know of executing a raw SQL query. But I didn't look into whether there is way of writing it with Active Record. I'll see if I can find anything.

**Comment by mec** [comment]
No! I like it, I just wondered you reached for it specifically or arrived there by another route.

**Comment by lawrence-dxw** [comment]
Ah, okay! Well, anyway, I did find a more Rails-y way to write it, so thanks for the question. I've updated the PR.

**Comment by mec** [comment]
Wow! Yeah that is a rails-y way! 👍 You got the standardrb blues though…

**Comment by lawrence-dxw** [comment]
D'oh, fixed 🙂

**Pull request merged**
