### PR TITLE
Add Rollbar access token and environment to ARM templates

### PR DESCRIPTION
**Pull request by robbiepaul**

### CODE REVIEW

**Comment by robbiepaul** [comment]
[Set up Rollbar on Azure "development" and "production" environments](https://trello.com/c/TdYbo1Jz/434-set-up-rollbar-on-azure-development-and-production-environments)

**Comment by erbridge** [comment]
This looks good, but I think we also need to add the reference to the `appSettings` for the app service.

**Comment by robbiepaul** [comment]
Ah yes, thanks!

**Comment by robbiepaul** [comment]
I've added those two references in `appSettings`

**Pull request merged**
