### PR TITLE
Release 010

### PR DESCRIPTION
**Pull request by robbiepaul**
- Fix deployment template conflict
- Make closed schools ineligible for current school
- Exclude closed schools from current school search

### CODE REVIEW

**Comment by robbiepaul** [comment]
> Yanked releases are versions that had to be pulled because of a serious bug or security issue

We didn't have to pull it, it just didn't deploy. It does raise a question of what we do in these circumstances though. I think another release with the fix is fine?

**Comment by erbridge** [comment]
Hrmm. Maybe `[UNRELEASED]` instead?

**Comment by robbiepaul** [comment]
Yeah ok, although the changes are released. Shall I duplicate the changes from 009 in to 010?

**Comment by erbridge** [comment]
Ok, nevermind. I see why we wouldn't do this. Leave as it is.

**Pull request merged**
