### PR TITLE
Format currency to 2 decimal places in CSV rows

### PR DESCRIPTION
**Pull request by erbridge**

### CODE REVIEW

**Comment by tekin** [comment]
What's the rationale for this one?

**Comment by erbridge** [comment]
I was taking a quick glance at the bug about the number input not always showing 2 decimal places and noticed that the CSV was also only showing 1 decimal place. I assert that it's easier to parse currencies by eye if they have 2 decimal places. The comma was a bonus, but also easier to parse.

If you don't think this change is appropriate, fine to close. Just felt like an easy improvement.

**Comment by tekin** [comment]
Yeah, I think it's probably not worth messing with the formatting too much now, at least until we understand more about the rest of the flow for claim processing and handing off for payment/payroll, etc. For example we may find that the commas cause issues for systems we pass the data onto.

**Comment by erbridge** [comment]
Fair enough.

**Pull request closed without merging**
